name: Webscraper
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - run: dotnet publish Webscraper_Goossens_Miel/Webscraper_Goossens_Miel.csproj -c Release --self-contained -r win-x64 -p:PublishSingleFile=true
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}